### ISSUE TITLE
print channels to csv gives lat long only

### ISSUE THREAD

**Issue by BenjiDa** [LSDtopotools/LSDTopoTools2#2]
I know this is brand new and still the beta version. LSDTT2 seems a lot more straight forward, so thanks for that. Thought i would point out some small problems as I work through the examples. 

Running `lsdtt-basic-metrics WA_BasicMetrics03.driver` gives WA_ThirdExample_CN.csv  in lat long not utm. The hillshade is in utm.

**Comment by simon-m-mudd** [comment]
I think I emailed about this and didn't respond here. Sorry. 
The csv file doesn't retain georeferencing so the rationale is that we use lat-long in EPSG:4326 (the WGS 1984 geographic coordinate system) so that you only ever need to use that projection when loading csv files, rather than having to check the UTM zone. So this is by design.
